In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import statistics

In [5]:
import numpy as np


def readucr(filename):
    data = np.loadtxt(filename, delimiter="\t")
    y = data[:, 1]
    x = data[:, 2:]
    print(f"x is: {x}")
    print(f"y is: {y}")
    return x, y.astype(int)


#root_url = "data/"
#x_train, y_train = readucr(root_url + "bq-results-train-data-only.csv")
#x_test, y_test = readucr(root_url + "bq-results-train-data-only.csv")
root_url = "https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA/"

x_train, y_train = readucr(root_url + "FordA_TRAIN.tsv")
x_test, y_test = readucr(root_url + "FordA_TEST.tsv")



x is: [[-0.66439208 -0.37301463  0.04081512 ... -0.66439208 -1.0737958
  -1.5643427 ]
 [ 0.63462859  0.37347448  0.03834345 ... -0.71488505 -0.56044294
  -0.31908642]
 [ 0.11128392 -0.49912439 -1.0686291  ...  0.39446303  0.33940042
   0.25539062]
 ...
 [-0.33316523 -0.29351853 -0.42534381 ... -1.3937145  -0.94273327
  -0.27072168]
 [ 2.0791499   2.0220362   1.8675596  ... -0.43214504 -0.44123126
  -0.28070891]
 [-0.32536268 -0.48823697 -0.59904489 ...  0.55576053  0.57445102
   0.57311598]]
y is: [-0.79717168  0.80485472  0.7279851  ... -0.57005428  2.0067321
 -0.12524091]
x is: [[ 0.17164128  0.30204415  0.23280369 ... -0.69040244 -0.97659635
  -0.79426313]
 [ 0.32225332  0.45384397  0.67185236 ... -1.0417721  -1.1596145
  -1.3756589 ]
 [ 0.74436655  0.72591291  0.66132516 ... -3.6752806  -4.1366217
  -4.3396117 ]
 ...
 [ 0.59397882  0.3818858   0.12728536 ... -0.12655282 -0.11782239
  -0.18909413]
 [-0.14062427 -0.27059412 -0.37883494 ... -1.0007084  -1.0841075
  -1.109963  ]
 [-0.2

In [6]:
x_train, y_train = readucr(root_url + "FordA_TRAIN.tsv")
x_test, y_test = readucr(root_url + "FordA_TEST.tsv")


#print(f"x train is: {x_train.shape(0)}")
#print(f"y train is: {y_train}")
type(x_train)

x is: [[-0.66439208 -0.37301463  0.04081512 ... -0.66439208 -1.0737958
  -1.5643427 ]
 [ 0.63462859  0.37347448  0.03834345 ... -0.71488505 -0.56044294
  -0.31908642]
 [ 0.11128392 -0.49912439 -1.0686291  ...  0.39446303  0.33940042
   0.25539062]
 ...
 [-0.33316523 -0.29351853 -0.42534381 ... -1.3937145  -0.94273327
  -0.27072168]
 [ 2.0791499   2.0220362   1.8675596  ... -0.43214504 -0.44123126
  -0.28070891]
 [-0.32536268 -0.48823697 -0.59904489 ...  0.55576053  0.57445102
   0.57311598]]
y is: [-0.79717168  0.80485472  0.7279851  ... -0.57005428  2.0067321
 -0.12524091]
x is: [[ 0.17164128  0.30204415  0.23280369 ... -0.69040244 -0.97659635
  -0.79426313]
 [ 0.32225332  0.45384397  0.67185236 ... -1.0417721  -1.1596145
  -1.3756589 ]
 [ 0.74436655  0.72591291  0.66132516 ... -3.6752806  -4.1366217
  -4.3396117 ]
 ...
 [ 0.59397882  0.3818858   0.12728536 ... -0.12655282 -0.11782239
  -0.18909413]
 [-0.14062427 -0.27059412 -0.37883494 ... -1.0007084  -1.0841075
  -1.109963  ]
 [-0.2

numpy.ndarray

In [7]:
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

print(f"x train is: {x_train}")

x train is: [[[-0.66439208]
  [-0.37301463]
  [ 0.04081512]
  ...
  [-0.66439208]
  [-1.0737958 ]
  [-1.5643427 ]]

 [[ 0.63462859]
  [ 0.37347448]
  [ 0.03834345]
  ...
  [-0.71488505]
  [-0.56044294]
  [-0.31908642]]

 [[ 0.11128392]
  [-0.49912439]
  [-1.0686291 ]
  ...
  [ 0.39446303]
  [ 0.33940042]
  [ 0.25539062]]

 ...

 [[-0.33316523]
  [-0.29351853]
  [-0.42534381]
  ...
  [-1.3937145 ]
  [-0.94273327]
  [-0.27072168]]

 [[ 2.0791499 ]
  [ 2.0220362 ]
  [ 1.8675596 ]
  ...
  [-0.43214504]
  [-0.44123126]
  [-0.28070891]]

 [[-0.32536268]
  [-0.48823697]
  [-0.59904489]
  ...
  [ 0.55576053]
  [ 0.57445102]
  [ 0.57311598]]]


In [17]:
n_classes = len(np.unique(y_train))
print(n_classes)


6


In [9]:
idx = np.random.permutation(len(x_train))
x_train = x_train[idx]
y_train = y_train[idx]

In [10]:
y_train[y_train == -1] = 0
y_test[y_test == -1] = 0

In [11]:
print(f"x_train: {x_train}")
print(f"y_train: {y_train}")

x_train: [[[-0.3456689 ]
  [-0.75012875]
  [-1.125885  ]
  ...
  [ 0.91207076]
  [ 0.9172896 ]
  [ 0.87032006]]

 [[ 1.2169933 ]
  [ 1.5955059 ]
  [ 1.6901341 ]
  ...
  [ 0.46091429]
  [ 1.3400099 ]
  [ 1.9361673 ]]

 [[ 1.6622896 ]
  [ 1.3117216 ]
  [ 0.76864539]
  ...
  [-0.14378917]
  [ 0.26509931]
  [ 0.67144833]]

 ...

 [[ 0.03842955]
  [-0.03604911]
  [-0.14474174]
  ...
  [ 2.228234  ]
  [ 2.2337347 ]
  [ 2.0797168 ]]

 [[ 1.0147185 ]
  [ 0.92108795]
  [ 0.73781112]
  ...
  [-1.2224541 ]
  [-1.1148785 ]
  [-0.87382966]]

 [[-0.17637349]
  [-0.62232784]
  [-0.9604686 ]
  ...
  [ 0.23260053]
  [ 0.05249432]
  [-0.15635623]]]
y_train: [0 0 1 ... 0 1 0]


In [12]:
from tensorflow import keras
from tensorflow.keras import layers

In [13]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Normalization and Attention
    x = layers.LayerNormalization(epsilon=1e-6)(inputs)
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(x, x)
    x = layers.Dropout(dropout)(x)
    res = x + inputs

    # Feed Forward Part
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    return x + res

In [14]:
def build_model(
    input_shape,
    head_size,
    num_heads,
    ff_dim,
    num_transformer_blocks,
    mlp_units,
    dropout=0,
    mlp_dropout=0,
):
    inputs = keras.Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    for dim in mlp_units:
        x = layers.Dense(dim, activation="relu")(x)
        x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(n_classes, activation="softmax")(x)
    return keras.Model(inputs, outputs)

In [15]:
#print(f"x_train shape: {x_train.shape}")
print(f"x_train shape: {x_train}")

x_train shape: [[[-0.3456689 ]
  [-0.75012875]
  [-1.125885  ]
  ...
  [ 0.91207076]
  [ 0.9172896 ]
  [ 0.87032006]]

 [[ 1.2169933 ]
  [ 1.5955059 ]
  [ 1.6901341 ]
  ...
  [ 0.46091429]
  [ 1.3400099 ]
  [ 1.9361673 ]]

 [[ 1.6622896 ]
  [ 1.3117216 ]
  [ 0.76864539]
  ...
  [-0.14378917]
  [ 0.26509931]
  [ 0.67144833]]

 ...

 [[ 0.03842955]
  [-0.03604911]
  [-0.14474174]
  ...
  [ 2.228234  ]
  [ 2.2337347 ]
  [ 2.0797168 ]]

 [[ 1.0147185 ]
  [ 0.92108795]
  [ 0.73781112]
  ...
  [-1.2224541 ]
  [-1.1148785 ]
  [-0.87382966]]

 [[-0.17637349]
  [-0.62232784]
  [-0.9604686 ]
  ...
  [ 0.23260053]
  [ 0.05249432]
  [-0.15635623]]]


In [16]:
input_shape = x_train.shape[1:]
print(f"x_train shape: {type(x_train.shape[1:])}")
print(f"x_train shape: {x_train.shape[1:]}")

model = build_model(
    input_shape,
    head_size=256,
    num_heads=4,
    ff_dim=4,
    num_transformer_blocks=4,
    mlp_units=[128],
    mlp_dropout=0.4,
    dropout=0.25,
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    metrics=["sparse_categorical_accuracy"],
)
model.summary()

callbacks = [keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]

model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=10,
    batch_size=64,
    callbacks=callbacks,
)

model.evaluate(x_test, y_test, verbose=1)

x_train shape: <class 'tuple'>
x_train shape: (499, 1)
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 499, 1)]     0           []                               
                                                                                                  
 layer_normalization (LayerNorm  (None, 499, 1)      2           ['input_1[0][0]']                
 alization)                                                                                       
                                                                                                  
 multi_head_attention (MultiHea  (None, 499, 1)      7169        ['layer_normalization[0][0]',    
 dAttention)                                                      'layer_normalization[0][0]']    
                                       

InvalidArgumentError:  Received a label value of -2 which is outside the valid range of [0, 7).  Label values: 0 -2 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 -2 0 0 0 0 0 0 0 -2 0 0 0 0 0 0 -2 0 0 0 0 0 0 0 0 0 1 0 0 0 -2 0 0 0 0 0 0 0 1 1 0 0
	 [[node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits
 (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\backend.py:5113)
]] [Op:__inference_train_function_5012]

Errors may have originated from an input operation.
Input Source operations connected to node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits:
In[0] sparse_categorical_crossentropy/Reshape_1 (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\backend.py:5109)	
In[1] sparse_categorical_crossentropy/Reshape (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\backend.py:3561)

Operation defined at: (most recent call last)
>>>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
>>>     app.start()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
>>>     self.io_loop.start()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
>>>     self._run_once()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
>>>     handle._run()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 81, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
>>>     lambda f: self._run_callback(functools.partial(callback, future))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
>>>     ret = callback()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 814, in inner
>>>     self.ctx_run(self.run)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 775, in run
>>>     yielded = self.gen.send(value)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 381, in dispatch_queue
>>>     yield self.process_one()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 250, in wrapper
>>>     runner = Runner(ctx_run, result, future, yielded)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 741, in __init__
>>>     self.ctx_run(self.run)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 775, in run
>>>     yielded = self.gen.send(value)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
>>>     yield gen.maybe_future(dispatch(*args))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
>>>     yield gen.maybe_future(handler(stream, idents, msg))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
>>>     self.do_execute(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
>>>     return runner(coro)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
>>>     if (await self.run_code(code, result,  async_=asy)):
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "<ipython-input-16-de6afb484236>", line 25, in <module>
>>>     model.fit(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 809, in train_step
>>>     loss = self.compiled_loss(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
>>>     loss_value = loss_obj(y_t, y_p, sample_weight=sw)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\losses.py", line 141, in __call__
>>>     losses = call_fn(y_true, y_pred)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\losses.py", line 245, in call
>>>     return ag_fn(y_true, y_pred, **self._fn_kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\losses.py", line 1737, in sparse_categorical_crossentropy
>>>     return backend.sparse_categorical_crossentropy(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend.py", line 5113, in sparse_categorical_crossentropy
>>>     res = tf.nn.sparse_softmax_cross_entropy_with_logits(
>>> 